### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by pautasso** [ogs-at-usi/handshake#28]
Does the project has a clear goal? yes
Did the project define use cases? yes
Did the project define screen mockups? yes
Did every team member present? yes (3 live, 2 recorded)
Did every team member contribute to the team progress? yes
Did the project demonstrate a walking skeleton? no
Was there a single integrated demo showing everyone's contributions? no
Did the project identify meaningful stretch goals? yes
Is the project team organized and working well together? yes
Is there a task board (trello, github project)? no

M1: 28/11/2022 Grade: 9/10

**Comment by micheledallerive** [comment]
Thank you for your feedback. 
Although we didn't have an actual task board, during the presentation we forgot the show that we have been organizing the work using the school whiteboard and Excel, and we kept track of the progress using our Discord server. 
However, in the next few days, we will move everything to the GitHub project to comply with the requirement.
