### ISSUE TITLE
[BUG] The frontend is not responsive (M2/M3)

### ISSUE THREAD

**Issue by micheledallerive** [ogs-at-usi/handshake#30]
**Describe the bug**
- The frontend components are not responsive (width/heights set with `vw`).
- The spaces are created using `<br/>` elements (instead of css `gap`)
- The two main sections (chats list and chat) could be implemented as `col-*` (for example, the left column could be col-12 col-md-4 col-lg-3, to make it 100% for smartphones, 33% for tablets and 25% for computer and bigger devices. It could be useful also a `max-width` property)
- The Bootstrap classes could be used to make the code easier to read, adapt and understand, since the majority of the components are unique and creating a specific class is not useful.

**To Reproduce**
1. Take the code of the views.
2. Put them together in a temporary HTML file.
3. Open the file.

**Target**
Milestone 2/3(?)

**Screenshots**
![localhost_8888_(iPhone 12 Pro)](https://user-images.githubusercontent.com/25416845/204559067-c89377e5-ec0d-4292-a8e1-c563f9d5a605.png)

**Comment by cosmcif** [comment]
Login page should work now.

![image](https://user-images.githubusercontent.com/75504103/204813432-eabfd437-755e-4b64-8ad2-bad6918d03f5.png)

Working on chat page now.
