### ISSUE TITLE
[BUG] Group creation opens group chat to everyone

### ISSUE THREAD

**Issue by micheledallerive** [ogs-at-usi/handshake#86]
**Describe the bug**
When someone creates a group, the group become the active chat in every member's browser. 

**To Reproduce**
1. Create 2 handshake accounts
2. Keep them both open at the same time
3. Create a group with one account
4. The group will become the active chat for every group member.

**Expected behavior**
The group should become the active chat only for the user that created the group, not for everyone.

**Additional context**
It's my fault lmao Jef fix plz

**Comment by JekxDevil** [comment]
No such behavior found, signed as closed for now.
